### ISSUE TITLE
Problem with FunctionSeries and padding

### ISSUE THREAD

**Issue by wadjih-bencheikh18** [zakodium-oss/react-plot#333]
https://zakodium.github.io/react-plot/?path=/story/examples-iris-dataset--pca
when we add padding in x Axis the plot will start zoom out

**Comment by targos** [comment]
I don't understand what's the bug?

**Comment by wadjih-bencheikh18** [comment]
when we add padding to x axis
functionSeries start from `min-padding` so this last will be the new min ...etc 

https://user-images.githubusercontent.com/56769876/153931048-60ff018d-5a8b-460c-869b-0d271e897866.mp4

**Comment by wadjih-bencheikh18** [comment]
i think we should force function serie to not change Axis min/max (because we're using LineSeries)

**Comment by targos** [comment]
> Padding should only be used when min and / or max are undefined

This is implemented in https://github.com/zakodium/react-plot/commit/4664c209eadf01303b5031329f69c0b90a0e3abf.

But we still have an issue with FunctionSeries because it is possible to render one without specifying min/max on the axis (for example when there are other series in the plot). In that case, and when there is padding, the LineSeries rendered internally by FunctionSeries will increase the automatic boundaries and we end up with the infinite loop.

I'm going to implement https://github.com/zakodium/react-plot/issues/316#issuecomment-1042815972 first and this should either be fixed as a result, or easy to fix afterwards.

**Comment by wadjih-bencheikh18** [comment]
@targos issue fixed
